const ESTADOS_CONTRATO = {
  PENDIENTE: "PENDIENTE",
  ENVIADO: "ENVIADO",
  VISTO: "VISTO",
  FIRMADO: "FIRMADO",
  VALIDADO: "VALIDADO",
  BLOQUEADO: "BLOQUEADO"
};

module.exports = { ESTADOS_CONTRATO };